[features]
seeds = false
skip-lint = false

[programs.devnet]
# Replace with your program ID
example_verify = "EWcLKpkJawAEbf5woiMumJyXuv314uWXifoby37o2mkt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
